name: Test

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and test linux
    runs-on: ubuntu-22.04
    env:
      RELEASE_OS: linux
    steps:
      - name: checkout branch
        uses: actions/checkout@master
      - name: Setup environment
        id: setup
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF##*/}
      - name: make
        run: |
          mkdir build && cd build && cmake .. -DZLIBNG=ON -DBUILD_FUNCTESTING=ON && make && make install && cd ..
      - name: Functional testing
        run: |
          cd build && make test
